export const personalInfo = {
  name: "Nitij Taneja",
  title: "AI Developer & Data Scientist",
  email: "tanejanitij4002@gmail.com",
  phone: "+91-7023108081",
  location: "India",
  photo: "/nitij-photo.png",
  github: "https://github.com/nitij-taneja",
  linkedin: "https://www.linkedin.com/in/nitij-taneja-702645204",
  linkedinActivity: "https://www.linkedin.com/in/nitij-taneja-702645204/recent-activity/all/",
  kaggle: "https://kaggle.com/nitijtaneja",
  hackerrank: "https://www.hackerrank.com/profile/tanejanitij4002",
  leetcode: "https://leetcode.com/u/nitijtaneja/",
  youtube: "https://www.youtube.com/@data_science_insights/featured",
  youtubeShorts: "https://www.youtube.com/shorts/AldeaWzbRwQ",
  instagram: "https://instagram.com/data_scienceinsights",
  geeksforgeeks: "https://www.geeksforgeeks.org/user/tanejanibzzy/",
  stackabuse: "https://stackabuse.com/author/nitij/",
  greeting: {
    hindi: "नमस्कार",
    english: "Hello",
    punjabi: "ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ",
  },
  bio: `A passionate AI Developer and Data Scientist with expertise in AI, Machine Learning, and Data Science. Currently pursuing an Integrated M.Tech in Computer Science and Engineering (Specialization: Computational Thinking and Data Science) at VIT Bhopal University (2022–2027). Exploring advanced topics in Generative AI, LLMs, and NLP, with hands-on experience in Agentic AI, RAG, and GraphRAG. I constantly explore the boundaries between technology and creativity, building AI systems that solve real-world problems.`,
  shortBio: `4th year Integrated M.Tech student with hands-on experience in Agentic AI, RAG, LLMs, and Generative AI. Proven ability to apply skills in parallel, gaining real-world startup experience alongside a rigorous education.`,
};

export const typingRoles = [
  "AI Developer",
  "Data Scientist",
  "Generative AI & LLMs",
  "Machine Learning Engineer",
  "Agentic AI Specialist",
  "Backend Developer",
];

export const experience = [
  {
    id: 1,
    company: "Blue Briar Consulting OPC Private Ltd",
    role: "Junior Data Scientist",
    location: "Remote",
    period: "Aug 2024 – Oct 2024",
    description: [
      "Developed practical coursework for Generative AI, focusing on LangChain, CrewAI, and Agentic AI frameworks",
      "Built multi-agent orchestration prototypes using the Google AI SDK (ADK) with RAG, sequential, and parallel agent workflows",
      "Built organization RBAC AI chat feature with multi-agent orchestration",
      "Worked on testing voice RAG models with STT, TTS, and RAG integration",
    ],
    techStack: ["LangChain", "CrewAI", "Google AI SDK", "RAG", "Python", "Multi-Agent Systems"],
    current: false,
    links: [],
  },
  {
    id: 2,
    company: "ApexIQ AI Solutions and Innovations Pvt Ltd",
    role: "Data Science Intern → Project Head",
    location: "Remote",
    period: "Oct 2024 – July 2025",
    description: [
      "Promoted to Project Head; led backend for Tattvaiq (Call Analytics) using Django, Whisper, & Mixtral",
      "Built Django backend APIs for VyasaIq (AI Accounting) and FastAPI backend for CitizenU (Microblogging)",
      "Developed API for nude detection and content moderation",
      "Built Explore section and feed management for CitizenU platform",
      "Worked with AWS Secret Manager for production deployment",
      "Led backend email integration, Calendly integration, and Google Sheet automation",
      "Supervised and mentored team of 2 interns with task delegation and code reviews",
    ],
    techStack: ["Django", "FastAPI", "AWS", "Whisper", "Mixtral", "PostgreSQL", "Python"],
    current: false,
    links: [
      { label: "Tattvaiq", url: "https://tattvaiq.com/" },
      { label: "VyasaIq", url: "https://vyasaiq.com/" },
      { label: "CitizenU", url: "https://www.citizenu.me/" },
    ],
  },
  {
    id: 3,
    company: "CloudyML E-Learning Pvt Ltd",
    role: "Data Science Intern",
    location: "Remote",
    period: "Dec 2023 – Mar 2024",
    description: [
      "Mentored 100+ learners in Python, R, Statistics, Machine Learning, Deep Learning, and NLP",
      "Provided coding guidance through Zoom sessions, data science concepts, and help with project implementation and deployment workflows",
      "Created educational video tutorials and written blog content explaining foundational to advanced ML topics",
    ],
    techStack: ["Python", "R", "Machine Learning", "Deep Learning", "NLP"],
    current: false,
    links: [],
  },
];

export const education = [
  {
    id: 1,
    degree: "Integrated M.Tech in Computer Science and Engineering",
    specialization: "Data Science and Computational Thinking",
    institution: "VIT Bhopal University",
    location: "Bhopal, Madhya Pradesh",
    period: "2022 – 2027 (Ongoing)",
    grade: "CGPA: 8.56",
    logo: "https://upload.wikimedia.org/wikipedia/en/c/c5/Vellore_Institute_of_Technology_seal_2017.svg",
  },
  {
    id: 2,
    degree: "Senior Secondary (Class XII)",
    specialization: "Science Stream",
    institution: "Apex International School",
    location: "Jaipur, Rajasthan",
    period: "2022",
    grade: "77.6% (CBSE Board)",
    logo: null,
  },
  {
    id: 3,
    degree: "Secondary School (Class X)",
    specialization: null,
    institution: "U.C.S.K.M Public School",
    location: "Bhiwadi, Rajasthan",
    period: "2020",
    grade: "91% (CBSE Board)",
    logo: null,
  },
];

export const projects = [
  {
    id: 1,
    title: "FinSight AI",
    description: "A multi-agent AI for Real-Time Financial Intelligence. Leverages multiple specialized agents to analyze market data, news, and trends to provide actionable financial insights with semantic deduplication and entity extraction.",
    github: "https://github.com/nitij-taneja/FinSight-AI",
    demo: "https://github.com/nitij-taneja/FinSight-AI/blob/main/Recording%202025-12-03%20174904-VEED.gif",
    liveLink: "https://nitij-taneja-finsight-ai-streamlit-app-grxwtf.streamlit.app/",
    videoLink: "https://youtu.be/b_bzwaWgW90?si=bbQ4ZJikrheW649l",
    tags: ["Multi-Agent AI", "LangChain", "Financial Analysis", "RAG", "Python", "Streamlit"],
    featured: true,
    category: "Agentic AI",
  },
  {
    id: 2,
    title: "A2A Legal Research",
    description: "A multi-agent AI for legal case research, synthesizing and delivering legal verdicts with transparency. Uses agent-to-agent communication for complex legal reasoning.",
    github: "https://github.com/nitij-taneja/A2A_LEGAL_RESEARCH",
    demo: "https://github.com/nitij-taneja/A2A_LEGAL_RESEARCH/blob/main/agentic-legal-research_q7LIi0wV%20(online-video-cutter.com).gif",
    liveLink: null,
    videoLink: null,
    tags: ["Multi-Agent", "Legal AI", "A2A Protocol", "LLMs", "Python"],
    featured: true,
    category: "Agentic AI",
  },
  {
    id: 3,
    title: "Graph RAG",
    description: "A knowledge graph application that combines document processing with AI-powered querying using Google Gemini. Implements advanced retrieval with graph-based context using Neo4j.",
    github: "https://github.com/nitij-taneja/graph_rag",
    demo: "https://github.com/nitij-taneja/graph_rag/blob/main/graph-rag-demo-personal-microsoft-edge-2025-11-22-01-03-55_Jt76sPeg-VEED.gif",
    liveLink: null,
    videoLink: null,
    tags: ["GraphRAG", "Knowledge Graphs", "Gemini", "Neo4j", "Python"],
    featured: true,
    category: "RAG",
  },
  {
    id: 4,
    title: "Deep Research AI Agent",
    description: "Autonomous research platform using LangGraph and Gemini for structured reports. Performs multi-step research with Tavily web search and document synthesis with Mermaid diagrams.",
    github: "https://github.com/nitij-taneja/deep-research-ai-agent",
    demo: "https://raw.githubusercontent.com/nitij-taneja/deep-research-ai-agent/main/VID_20251029185139_V1.gif",
    liveLink: "https://deep-research-ai-agent-by-nitijtaneja.streamlit.app/",
    videoLink: "https://drive.google.com/file/d/1lP8jjhbhY9xwZifkO95IHL2EoXjzukaQ/view?usp=drivesdk",
    tags: ["LangGraph", "Research AI", "Gemini", "Tavily", "Streamlit", "Python"],
    featured: true,
    category: "Agentic AI",
  },
  {
    id: 5,
    title: "ReAct RAG Visualizer",
    description: "Interactive AI observability tool visualizing the step-by-step ReAct reasoning loop (Thought, Action, Observation). Debug and understand how AI agents think and act in real-time.",
    github: "https://github.com/nitij-taneja/react_rag_visualiser",
    demo: "https://raw.githubusercontent.com/nitij-taneja/react_rag_visualiser/main/%25VITE_APP_TITLE%25%20-%20Personal%20-%20Microsoft_%20Edge%202025-11-15%2020-52-22-VEED.gif",
    liveLink: null,
    videoLink: "https://drive.google.com/file/d/1AXsgS8ejC0sci058VNNgkWBDrO90qLMa/view?usp=sharing",
    tags: ["ReAct", "RAG", "Visualization", "LangChain", "Gemini", "FastAPI"],
    featured: true,
    category: "RAG",
  },
  {
    id: 6,
    title: "AI Newsletter Agent",
    description: "Production-ready web app demonstrating modern agentic AI frameworks. Generates personalized newsletters with real-time visualization of multi-agent collaboration using GROQ and Tavily.",
    github: "https://github.com/nitij-taneja/The-AI-Samachar",
    demo: "https://github.com/nitij-taneja/The-AI-Samachar/blob/main/AI%20Newsletter%20Agent%20and%202%20more%20pages%20-%20Personal%20-%20Microsoft_%20Edge%202025-12-06%2015-43-28.gif",
    liveLink: null,
    videoLink: "https://youtu.be/aD5G2eUrI9c?si=ubuSNX3kFuHwxFjF",
    tags: ["Multi-Agent", "GROQ", "Tavily", "Newsletter AI", "Python"],
    featured: true,
    category: "Agentic AI",
  },
  {
    id: 7,
    title: "Reactive vs Proactive Agents",
    description: "Dual-agent system orchestrating Groq (Llama 3) for drafting and Gemini for strategic refinement. Demonstrates multi-LLM collaboration patterns with real-time web search.",
    github: "https://github.com/nitij-taneja/Reactive-vs-Proactive-Agents",
    demo: "https://raw.githubusercontent.com/nitij-taneja/Reactive-vs-Proactive-Agents/main/dual-agent-ai-content-strategist-streamlit-personal-microsoft-edge-2025-10_bdmLVHc6.gif",
    liveLink: null,
    videoLink: "https://drive.google.com/file/d/18NkvcrkhxUuKaDemVEWJkCnZKjomAphC/view?usp=sharing",
    tags: ["Dual-Agent", "Groq", "Gemini", "LangChain", "Tavily", "Streamlit"],
    featured: true,
    category: "Agentic AI",
  },
  {
    id: 8,
    title: "Research Paper Classification",
    description: "NLP system using Sentence Transformers to classify papers and recommend academic venues. Analyzes readability, sentiment, and semantic similarity for publishability assessment.",
    github: "https://github.com/nitij-taneja/Research-Paper-classification-MVP",
    demo: "https://raw.githubusercontent.com/nitij-taneja/Research-Paper-classification-MVP/main/my_preview.gif",
    liveLink: null,
    videoLink: "https://drive.google.com/file/d/1bvVasGnSLw6zGj14-hLn-y_Jed9EWdud/view?usp=sharing",
    tags: ["NLP", "Sentence Transformers", "Flask", "Scikit-learn", "Python"],
    featured: true,
    category: "Data Science",
  },
  {
    id: 9,
    title: "SmartShop.ai",
    description: "AI-Enhanced E-Commerce Platform with an AI chatbot for real-time price negotiation via Together AI. Full-stack FastAPI & Streamlit implementation with smart bargaining engine.",
    github: "https://github.com/nitij-taneja/SmartShop.ai",
    demo: null,
    liveLink: null,
    videoLink: null,
    tags: ["FastAPI", "Streamlit", "Together AI", "E-Commerce", "Python", "NLP"],
    featured: true,
    category: "Full-Stack",
  },
  {
    id: 10,
    title: "SafeSphere",
    description: "Community Safety Risk Modeling System using CNN-LSTM hybrid model for spatiotemporal risk prediction. Features real-time alerts, incident reporting, and GPT-powered chatbot for rural student safety.",
    github: "https://github.com/nitij-taneja/SafeSphere",
    demo: null,
    liveLink: null,
    videoLink: null,
    tags: ["CNN-LSTM", "TensorFlow", "FastAPI", "GPT", "Docker", "AWS"],
    featured: true,
    category: "Data Science",
  },
];

export const skills = {
  genai: {
    title: "GenAI & Agentic AI",
    items: [
      { name: "LangChain", icon: "langchain" },
      { name: "LangGraph", icon: "langgraph" },
      { name: "GraphRAG", icon: "graphrag" },
      { name: "CrewAI", icon: "crewai" },
      { name: "Autogen", icon: "autogen" },
      { name: "Google AI SDK", icon: "google" },
      { name: "LLMs", icon: "llm" },
      { name: "RAG", icon: "rag" },
      { name: "LlamaIndex", icon: "llamaindex" },
      { name: "ReAct", icon: "react" },
      { name: "Prompt Engineering", icon: "prompt" },
      { name: "Generative AI", icon: "genai" },
    ],
  },
  ml: {
    title: "ML/DL & Algorithms",
    items: [
      { name: "PyTorch", icon: "pytorch" },
      { name: "TensorFlow", icon: "tensorflow" },
      { name: "Scikit-learn", icon: "sklearn" },
      { name: "Neural Networks", icon: "nn" },
      { name: "Transformers", icon: "transformers" },
      { name: "CNN", icon: "cnn" },
      { name: "LSTM", icon: "lstm" },
      { name: "HuggingFace", icon: "huggingface" },
      { name: "OpenCV", icon: "opencv" },
      { name: "Attention", icon: "attention" },
      { name: "Random Forest", icon: "rf" },
      { name: "SVM", icon: "svm" },
      { name: "KNN", icon: "knn" },
      { name: "PCA", icon: "pca" },
    ],
  },
  backend: {
    title: "Backend & DevOps",
    items: [
      { name: "FastAPI", icon: "fastapi" },
      { name: "Django", icon: "django" },
      { name: "Flask", icon: "flask" },
      { name: "Express.js", icon: "express" },
      { name: "Docker", icon: "docker" },
      { name: "Kubernetes", icon: "kubernetes" },
      { name: "AWS", icon: "aws" },
      { name: "Git/GitHub", icon: "git" },
      { name: "MLflow", icon: "mlflow" },
      { name: "LangSmith", icon: "langsmith" },
      { name: "CI/CD", icon: "cicd" },
      { name: "MLOps", icon: "mlops" },
    ],
  },
  languages: {
    title: "Programming Languages",
    items: [
      { name: "Python", icon: "python" },
      { name: "JavaScript", icon: "javascript" },
      { name: "TypeScript", icon: "typescript" },
      { name: "SQL", icon: "sql" },
      { name: "R", icon: "r" },
      { name: "C", icon: "c" },
      { name: "C++", icon: "cpp" },
      { name: "Java", icon: "java" },
    ],
  },
  frontend: {
    title: "Frontend & Frameworks",
    items: [
      { name: "React", icon: "react" },
      { name: "Node.js", icon: "nodejs" },
      { name: "Streamlit", icon: "streamlit" },
      { name: "HTML5", icon: "html" },
      { name: "CSS3", icon: "css" },
      { name: "Tailwind CSS", icon: "tailwind" },
    ],
  },
  data: {
    title: "Data Science & Visualization",
    items: [
      { name: "NumPy", icon: "numpy" },
      { name: "Pandas", icon: "pandas" },
      { name: "Matplotlib", icon: "matplotlib" },
      { name: "Seaborn", icon: "seaborn" },
      { name: "Tableau", icon: "tableau" },
      { name: "PowerBI", icon: "powerbi" },
    ],
  },
  databases: {
    title: "Databases & Cloud",
    items: [
      { name: "MySQL", icon: "mysql" },
      { name: "PostgreSQL", icon: "postgresql" },
      { name: "MongoDB", icon: "mongodb" },
      { name: "SQLite", icon: "sqlite" },
      { name: "Firebase", icon: "firebase" },
      { name: "Neo4j", icon: "neo4j" },
      { name: "Airflow", icon: "airflow" },
      { name: "Jenkins", icon: "jenkins" },
    ],
  },
};

export const achievements = [
  {
    id: 1,
    title: "Rank 23",
    subtitle: "Top 50/1500+",
    description: "Zelestra x AWS ML Ascend Challenge - Second Edition",
    icon: "trophy",
  },
  {
    id: 2,
    title: "Round 2 Qualifier",
    subtitle: "From 10k+ registrations",
    description: "IIT Kharagpur Data Science Hackathon (2024 & 2025)",
    icon: "medal",
  },
  {
    id: 3,
    title: "1st Place",
    subtitle: "Out of 40 teams",
    description: "Stock Quest Competition, VIT Bhopal",
    icon: "award",
  },
  {
    id: 4,
    title: "5k+ Views",
    subtitle: "Content Creator",
    description: "Data Science content on YouTube & Instagram",
    icon: "eye",
  },
];

export const certifications = [
  {
    id: 1,
    title: "Applied Machine Learning in Python",
    issuer: "University of Michigan (Coursera)",
    icon: "certificate",
  },
  {
    id: 2,
    title: "Data Science Masters",
    issuer: "PWskills",
    icon: "certificate",
  },
  {
    id: 3,
    title: "Technical Article (Under Review)",
    issuer: "Federated Learning on StackAbuse",
    icon: "article",
    link: "https://stackabuse.com/federated-learning-explained-collaborative-ai-without-data-sharing/",
  },
];

export const socialPreviews = [
  {
    id: 1,
    platform: "LinkedIn Activity",
    title: "Recent Activity",
    description: "Check out my latest posts and professional updates",
    link: "https://www.linkedin.com/in/nitij-taneja-702645204/recent-activity/all/",
    icon: "linkedin",
  },
  {
    id: 2,
    platform: "YouTube",
    title: "Data Science Insights",
    description: "Educational content on AI, ML, and Data Science",
    link: "https://www.youtube.com/@data_science_insights/featured",
    icon: "youtube",
  },
  {
    id: 3,
    platform: "YouTube Shorts",
    title: "Quick Tech Tips",
    description: "Short-form content on trending tech topics",
    link: "https://www.youtube.com/shorts/AldeaWzbRwQ",
    icon: "youtube",
  },
  {
    id: 4,
    platform: "StackAbuse",
    title: "Technical Articles",
    description: "In-depth articles on Machine Learning and AI",
    link: "https://stackabuse.com/author/nitij/",
    icon: "article",
  },
];

export const navLinks = [
  { label: "About", href: "#about" },
  { label: "Experience", href: "#experience" },
  { label: "Projects", href: "#projects" },
  { label: "Skills", href: "#skills" },
  { label: "Achievements", href: "#achievements" },
  { label: "Resume", href: "#resume" },
  { label: "Contact", href: "#contact" },
];
